"""Removing TestRunConfig tables and references

Revision ID: a292dc578e67
Revises: 96ee37627a48
Create Date: 2023-10-19 13:07:31.786684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a292dc578e67'
down_revision = '96ee37627a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_testrunexecution_test_run_config_id_testrunconfig',
        'testrunexecution',
        type_='foreignkey'
    )
    op.drop_column('testrunexecution', 'test_run_config_id')
    op.drop_index('ix_testrunconfig_id', table_name='testrunconfig')
    op.drop_table('testrunconfig')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'testrunconfig',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('dut_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'selected_tests',
            postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name='pk_testrunconfig')
    )
    op.create_index('ix_testrunconfig_id', 'testrunconfig', ['id'], unique=False)
    op.add_column(
        'testrunexecution',
        sa.Column(
            'test_run_config_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=True
        )
    )
    op.create_foreign_key(
        'fk_testrunexecution_test_run_config_id_testrunconfig',
        'testrunexecution',
        'testrunconfig',
        ['test_run_config_id'],
        ['id']
    )
    # ### end Alembic commands ###
